const projectsData = [
    {
        title: "Capstone II Project",
        description: "Payroll System with Generated QR Code for Employee Attendance Monitoring",
        image: "src/images/capstone.png",
        techStack: ["SCSS", "Javascript", "PHP", "MySQL"],
        githubLink: "https://github.com/VawnDyu/Capstone-Project",
    },
    {
      title: "Capstone I Project",
      description: "Barangay Clearance System and Queuing System",
      image: "src/images/bcqsystem.png",
      techStack: ["VB.Net", "Crystal Reports", "MySQL"],
      githubLink: "https://github.com/VawnDyu/Barangay-Clearance-System",
    },
    {
        title: "Dating Simulator Game",
        description: "A Visual Novel Dating Simulator Game (WIP)",
        image: "src/images/datingsimulatorgame.png",
        techStack: ["Python", "TKinter"],
        githubLink: "https://github.com/VawnDyu/Dating-Simulator-Game",
    },
    {
        title: "Guess the Picture",
        description: "Guess the Picture is a kid interactive game with timer and scoreboard",
        image: "src/images/gtp2.png",
        techStack: ["React", "CSS", "Javascript"],
        liveLink: "https://vawndyu.github.io/Guess-the-picture",
        githubLink: "https://github.com/VawnDyu/Guess-the-picture",
    },
    {
        title: "Doodle's Portfolio",
        description: "Doodle's Commissioned Portfolio for Social Media Assets",
        image: "src/images/portfolio1.png",
        techStack: ["React", "CSS", "Javascript"],
        liveLink: "https://vawndyu.github.io/Doodles-Portfolio",
        githubLink: "https://github.com/VawnDyu/Doodles-Portfolio",
    },
    {
        title: "Poke-Search",
        description: "A PokeDex that you can search any pokemon you want.",
        image: "src/images/pokesearch.png",
        techStack: ["React", "CSS", "Javascript", "PokeAPI"],
        liveLink: "https://vawndyu.github.io/PokeSearch",
        githubLink: "https://github.com/VawnDyu/PokeSearch",
    },
    {
        title: "Gacha",
        description: "A Gacha game that counts the amount of your gacha pulls.",
        image: "src/images/gacha.png",
        techStack: ["React", "CSS", "Javascript"],
        liveLink: "https://vawndyu.github.io/Gacha",
        githubLink: "https://github.com/VawnDyu/Gacha",
    },
    {
        title: "Vonne Dew's Portfolio",
        description: "A personal portfolio website built with React.",
        image: "src/images/vonnedewportfolio.png",
        techStack: ["React", "CSS", "Javascript", "Vite"],
        liveLink: "https://vawndyu.github.io/Gacha",
        githubLink: "https://github.com/VawnDyu/Gacha",
    },
  ];
  
  export default projectsData;